# auto_fork_sync.yml
name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: hect0x7
          auto_approve: true
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
