# auto_fork_sync.yml
name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: llvm
          base: master
          head: master
